sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 7.2
    env: WP_TRAVISCI=travis:phpvalidate
  - php: 7.2
    env: WP_TRAVISCI=travis:codecoverage
  - php: 7.2
    env: WP_TRAVISCI=travis:jshint
  - php: 7.2
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 7.1
    env: WP_TRAVISCI=travis:phpunit
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit
  fast_finish: true

cache:
  apt: true
  bundler: true
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

branches:
  only:
    - master

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require phpmd/phpmd
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    composer install --no-interaction
  - |
    if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
      npm install
      node --version
      npm --version
      grunt --version
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      grunt checktextdomain
      phpmd classes text codesize,naming,unusedcode
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
      phpunit --coverage-clover build/logs/clover.xml
    else
      phpunit
    fi
  - |
   if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
     grunt jshint
   fi

after_script:
  # Push coverage off to Codecov
- |
  if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  slack:
    rooms:
      secure: dVNKRk+6ptcuFn6SiT5SD0Rij5to3z3CETgNMAN1bdrczvYcMgyhZrW/51ihlGpMfdB45HuKI42tyLeNPOy6eMUg2weqonW5K+iVWw26toaVN5SV1hg7517A6f3GY5pLLCqV8uH5TKCvinGpPophf1upoHdTwnbAlQrlE2wPLg6oTsifqL73+mq5ieDizbu+1YJe6OHGhod7X64W8lB71QSN+6IXAbbqF1B7eCajzfa3BhAFRKSA7kCQwXuTNMCGhNPWeZBb8ljlcuTit9zFApmrDuI/JFK+ksDydhctygXrogZl8lj4Wg086vU4vphEPp+LJwU7T84J0shcxqVBI8/dW67ucZDP8Ghd5frj821EM41mnHz628nc1EFgIxgIdDr4bTQVh++bE5rnRMsi814p5tqu9gD1agbeXaQoZvqKofjamgLjV0JgEdsjl8L2+sKkgnq5KtZ0pZ919+G0xuUPlcAiuCa4SVLMJS64nxAYKEPIvlc1MU5Ue2yPCQBYD1hD552L0AyimEw9QExB3tBJm2XhwC6WHCi6m+T9E6+8n46a/he0HVAh89gLUpm3RHQc5i2THO7QLjIia4qG1pN4pQ7b+4lwCfuYzoSrDwxJ2BO8ha0tzLmcUl7EntxahmELQc48E/fxWgg374vOBTdqWVSrod4YvEdrcr1YKyQ=
    on_start: never
    on_failure: always
    on_success: change
